# Generated by Django 5.0 on 2024-01-09 07:45

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_saleitem_category_fundingitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainPageSlideBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=config.utils.upload_path
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fundingitem",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="fundingitem",
            name="bank_account_owner",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="fundingitem",
            name="bank_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="bank_account_owner",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="bank_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
