# Generated by Django 5.0 on 2024-01-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_mainpageslidebanner_fundingitem_bank_account_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundingitem",
            name="current_amount",
        ),
        migrations.AlterField(
            model_name="fundingitem",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
