# Generated by Django 5.0 on 2024-01-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_fundingitem_current_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingitem",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("idol", "아이돌"),
                    ("stationery", "문구"),
                    ("accessory", "악세사리"),
                    ("food", "푸드"),
                    ("interior", "인테리어"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("idol", "아이돌"),
                    ("stationery", "문구"),
                    ("accessory", "악세사리"),
                    ("food", "푸드"),
                    ("interior", "인테리어"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
