# Generated by Django 5.0 on 2024-01-22 06:32

import config.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="작성시간",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=config.utils.upload_path
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정됨"),
        ),
        migrations.AddField(
            model_name="notice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="작성시간",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정됨"),
        ),
    ]
