# Generated by Django 5.0 on 2024-01-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_event_created_at_event_image_event_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fundingitem",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("idol", "아이돌"),
                    ("subscription ", "구독상품"),
                    ("accessory", "악세사리"),
                    ("food", "푸드"),
                    ("interior", "인테리어"),
                    ("pet", "반려동물"),
                    ("etc", "기타"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("idol", "아이돌"),
                    ("subscription ", "구독상품"),
                    ("accessory", "악세사리"),
                    ("food", "푸드"),
                    ("interior", "인테리어"),
                    ("pet", "반려동물"),
                    ("etc", "기타"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
