# Generated by Django 5.0 on 2024-01-09 07:45

import django.db.models.deletion
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_mainpageslidebanner_fundingitem_bank_account_number_and_more"),
        ("user", "0002_authtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bank_account_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bank_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_creator",
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성시간"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정됨")),
                (
                    "id",
                    models.CharField(
                        default=user.models.generate_hex,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_paid", models.BooleanField()),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "shipping_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "shipping_phone_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "shipping_zipcode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "shipping_address1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_address2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "funding_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant",
                        to="core.fundingitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성시간"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정됨")),
                (
                    "id",
                    models.CharField(
                        default=user.models.generate_hex,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_paid", models.BooleanField()),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "shipping_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "shipping_phone_number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "shipping_zipcode",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "shipping_address1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_address2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sale_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase",
                        to="core.saleitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
