# Generated by Django 5.0 on 2024-01-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("internal", "INTERNAL"),
                    ("google", "GOOGLE"),
                    ("facebook", "FACEBOOK"),
                    ("kakao", "KAKAO"),
                    ("naver", "NAVER"),
                ],
                default="internal",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_uid",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
